name = "secret-worker"
compatibility_date = "2024-08-25"
workers_dev = false

[env.dev]
vars = { ENVIRONMENT = "dev" }
d1_databases = [ { binding = "DB", database_name = "cfw-d1-secret", database_id = "6f5f390d-58b7-4221-a11e-3da9c4ae9b67" }]

[env.production]
vars = { ENVIRONMENT = "production" }
d1_databases = [ { binding = "DB", database_name = "cfw-d1-secret", database_id = "6f5f390d-58b7-4221-a11e-3da9c4ae9b67" }]
routes = [
    { pattern = "secret.ahh.bet/api", zone_name = "ahh.bet" },
    { pattern = "secret.ahh.bet/api/*", zone_name = "ahh.bet" }
]
